name: "ERNIE-QNLI"
backend: "paddle"
input [
  {
    name: "eval_placeholder_0"
    data_type: TYPE_INT32
    dims: [ -1 ],
  },
  {
    name: "eval_placeholder_1"
    data_type: TYPE_INT32
    dims: [ -1 ],
  },
  {
    name: "eval_placeholder_2"
    data_type: TYPE_INT32
    dims: [ -1 ],
  },
  {
    name: "eval_placeholder_3"
    data_type: TYPE_INT32
    dims: [ 1, -1, 1 ],
  }
]
output [
  {
    name: "softmax_12.tmp_0"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]

instance_group [ { kind: KIND_CPU }]

optimization { 
  execution_accelerators { 
    cpu_execution_accelerator : [ 
      { 
        name : "ort"
        parameters { key: "cpu_threads" value: "4" }
      }
    ]
  }
}
